dist: xenial

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake pkg-config libglib2.0-dev libgpgme11-dev libgnutls28-dev uuid-dev libssh-gcrypt-dev libhiredis-dev libmicrohttpd-dev libxml2-dev libxslt1-dev

install:
  - git clone https://github.com/greenbone/gvm-libs.git
  - pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && sudo make install && popd

language: c

compiler:
  - gcc

before_script:
  - curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - curl --silent --show-error https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  - echo "deb http://deb.nodesource.com/node_6.x jessie main" | sudo tee /etc/apt/sources.list.d/nodesource.list
  - sudo apt-get update -qq
  - sudo apt-get install nodejs yarn

script:
  - mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && sudo make install
