version: 2
jobs:
  js_test:
    working_directory: ~/gsa
    docker:
      - image: circleci/node:6
        environment:
          ENV: CI
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "./ng/package.json"  }}
            - v1-deps
      - run:
          working_directory: ~/gsa/ng
          name: Install JavaScript dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "./ng/package.json"  }}
          paths:
            - ./ng/node_modules
      - run:
          working_directory: ~/gsa/ng
          name: Run JavaScript tests
          command: yarn test
  build_gsad:
    docker:
      - image: wiegandm/gsa-gsad-debian-stretch
    steps:
      - run:
          working_directory: ~/gvm-libs
          name: Checkout gvm-libs
          command: git clone https://github.com/greenbone/gvm-libs.git
      - run:
          working_directory: ~/gvm-libs
          name: Configure and compile gvm-libs
          command: pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install && popd
      - checkout
      - run:
          name: Configure and compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release -DSKIP_NG=1 .. && make install
  build_ng:
    docker:
      - image: wiegandm/gsa-ng-debian-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "./ng/package.json"  }}
            - v1-deps
      - run:
          name: Configure and compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release -DSKIP_GSAD=1 .. && make install
      - save_cache:
          key: v1-deps-{{ checksum "./ng/package.json"  }}
          paths:
            - ./ng/node_modules
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gsad
      - build_ng
      - js_test
