version: 2
jobs:
  js_test:
    working_directory: ~/gsa
    docker:
      - image: circleci/node:6
        environment:
          ENV: CI
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "./gsa/yarn.lock"  }}
            - v1-deps
      - run:
          working_directory: ~/gsa/gsa
          name: Install JavaScript dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "./gsa/yarn.lock"  }}
          paths:
            - ./gsa/node_modules
      - run:
          working_directory: ~/gsa/gsa
          name: Run JavaScript tests
          command: yarn test:coverage
      - run:
          working_directory: ~/gsa/gsa
          name: Submit test coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
  build_gsad:
    docker:
      - image: greenbone/build-env-gsa-master-debian-stretch-gcc-gsad
    steps:
      - run:
          working_directory: ~/gvm-libs
          name: Checkout gvm-libs
          command: git clone --depth 1 https://github.com/greenbone/gvm-libs.git
      - run:
          working_directory: ~/gvm-libs
          name: Configure and compile gvm-libs
          command: pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install && popd
      - checkout
      - run:
          name: Configure and compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release -DSKIP_GSA=1 .. && make install
  build_gsa:
    docker:
      - image: greenbone/build-env-gsa-master-debian-stretch-node6-ng
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "./gsa/yarn.lock"  }}
            - v1-deps
      - run:
          name: Configure and compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release -DSKIP_GSAD=1 .. && make install
      - save_cache:
          key: v1-deps-{{ checksum "./gsa/yarn.lock"  }}
          paths:
            - ./gsa/node_modules
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gsad
      - build_gsa
      - js_test
