version: 2
jobs:
  build:
    working_directory: ~/gsa
    docker:
      - image: circleci/node:6
        environment:
          ENV: CI
    branches:
      ignore:
        - /gsa-.*/
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "./ng/package.json"  }}
            - v1-deps
      - run:
          working_directory: ~/gsa/ng
          name: Install JavaScript dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "./ng/package.json"  }}
          paths:
            - ./ng/node_modules
      - run:
          working_directory: ~/gsa/ng
          name: Run JavaScript tests
          command: yarn test
