.TH gsad 8 User Manuals
.SH NAME
gsad \- Greenbone Security Assistant for the Open Vulnerability Assessment System (OpenVAS)
.SH SYNOPSIS
\fBgsad OPTIONS
\f1
.SH DESCRIPTION
Together, OpenVAS Scanner (openvassd(8)) and OpenVAS Manager (openvasmd(8)) provide the core functionality of the Open Vulnerability Assessment System (OpenVAS), with OpenVAS Scanner handling the actual scan process and OpenVAS Manager adding various management functionalities to handle and organise scan results. 

The Greenbone Security Assistant Daemon (gsad) is a web application that connects to the OpenVAS Manager and OpenVAS Administrator to provide for a full-featured user interface for vulnerability management. 
.SH OPTIONS
.TP
\fB-f, --foreground\f1
Run in foreground.
.TP
\fB--http-only\f1
Serve HTTP only, without SSL.
.TP
\fB--listen=\fIADDRESS\fB\f1
Listen on ADDRESS.
.TP
\fB--alisten=\fIADDRESS\fB\f1
Administrator address.
.TP
\fB--mlisten=\fIADDRESS\fB\f1
Manager address.
.TP
\fB-p, --port=\fIPORT\fB\f1
Listen on port number PORT.
.TP
\fB-a, --aport=\fIPORT\fB\f1
Use administrator port number PORT.
.TP
\fB-m, --mport=\fIPORT\fB\f1
Use manager port number PORT.
.TP
\fB-r, --rport=\fIPORT\fB\f1
Redirect HTTP from port number PORT.
.TP
\fB-R, --redirect\f1
Redirect HTTP to HTTPS.
.TP
\fB-k, --ssl-private-key=\fIFILE\fB\f1
Use FILE as the private key for HTTPS
.TP
\fB-c, --ssl-certificate=\fIFILE\fB\f1
Use FILE as the certificate for HTTPS
.TP
\fB--do-chroot\f1
Do chroot and drop privileges.
.TP
\fB-v, --verbose\f1
Print progress messages.
.TP
\fB-V, --version\f1
Print version.
.TP
\fB-?, --help\f1
Show help.
.SH EXAMPLES
gsad

Start gsad with the default port configuration and listen on port 443 for HTTPS requests. 
.SH SEE ALSO
\fBopenvassd(8)\f1 \fBopenvasad(8)\f1 \fBomp(8)\f1 \fBopenvasmd(8)\f1 \fBgsd(8)\f1
.SH MORE INFORMATION ABOUT THE OPENVAS PROJECT
The canonical places where you will find more information about the OpenVAS project are: \fBhttp://www.openvas.org/\f1 (Official site) \fBhttp://wald.intevation.org/projects/openvas/\f1 (Development Platform) 
.SH COPYRIGHT
The Greenbone Security Assistant is released under the GNU GPL, version 2, or, at your option, any later version. 
