/* SPDX-FileCopyrightText: 2026 Greenbone AG
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface Paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: Operations['health_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/key': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download the current feed key file. */
    get: Operations['download_key'];
    /** Upload a new feed key file. */
    put: Operations['upload_key'];
    /** Upload a new feed key as a multipart/form-data file upload. */
    post: Operations['upload_key_multipart'];
    /** Delete the current feed key. */
    delete: Operations['delete_key'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type Webhooks = Record<string, never>;
export interface Components {
  schemas: {
    JsonResponse: {
      message: string;
      status: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type Defs = Record<string, never>;
export interface Operations {
  health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health check OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "OK server is healthy",
           *       "status": "success"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
    };
  };
  download_key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Key downloaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Key not available */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key not available",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
    };
  };
  upload_key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The key file to upload */
    requestBody?: {
      content: {
        'application/octet-stream': unknown;
      };
    };
    responses: {
      /** @description Key uploaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key uploaded successfully",
           *       "status": "success"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Bad Request. Failed to validate key. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Bad request: Key upload failed. Failed to validate key. Invalid Key data",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Key upload failed. Could not write to file. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key upload failed. Could not write to file.",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
    };
  };
  upload_key_multipart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description File to upload */
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description Key upload successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key uploaded successfully",
           *       "status": "success"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Bad Request. Failed to validate key. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Bad request: Key upload failed. Failed to validate key. Invalid Key data",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Key upload failed. Could not write to file. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key upload failed. Could not write to file.",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
    };
  };
  delete_key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Key deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key deleted successfully",
           *       "status": "success"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
      /** @description Key deletion failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Key deletion failed",
           *       "status": "error"
           *     }
           */
          'application/json': Components['schemas']['JsonResponse'];
        };
      };
    };
  };
}
