#!/usr/bin/env node
/* SPDX-FileCopyrightText: 2026 Greenbone AG
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

import {execSync} from 'node:child_process';
import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

// eslint-disable-next-line @typescript-eslint/naming-convention
const __filename = fileURLToPath(import.meta.url);
// eslint-disable-next-line @typescript-eslint/naming-convention
const __dirname = dirname(__filename);

const OPENAPI_URL =
  'http://127.0.0.1:9392/service/feed-key/api/v1/openapi.json';
const OUTPUT_FILE = join(
  __dirname,
  '..',
  'src',
  'gmp',
  'commands',
  'feed-key-types.ts',
);

const YEAR = new Date().getFullYear();

const CUSTOM_HEADER = `/* SPDX-FileCopyrightText: ${YEAR} Greenbone AG
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
`;

try {
  console.info('Generating TypeScript types from OpenAPI spec...');

  // Generate the types
  execSync(`npx openapi-typescript ${OPENAPI_URL} -o ${OUTPUT_FILE}`, {
    stdio: 'inherit',
  });

  // Read the generated file
  let content = readFileSync(OUTPUT_FILE, 'utf8');

  // Remove the default header (first comment block)
  content = content.replace(/^\/\*\*[\s\S]*?\*\/\s*\n/, '');

  // Transform all exported types to PascalCase for code conventions
  // This general approach works regardless of what types openapi-typescript generates

  /**
   * Helper function to convert to PascalCase
   */
  const toPascalCase = (str: string): string => {
    // Remove $ prefix if present (e.g., $defs -> Defs)
    str = str.replace(/^\$/, '');
    // Handle already PascalCase names
    if (/^[A-Z]/.test(str)) {
      return str;
    }
    // Convert snake_case or kebab-case to PascalCase
    return str
      .split(/[_-]/)
      .map((word: string) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
  };

  // Collect all exported type/interface names and their PascalCase versions
  const typeMap: Map<string, string> = new Map();

  // Find all "export interface name {" and "export type name ="
  const exportPattern = /export\s+(interface|type)\s+(\$?[a-z_$]\w*)\s*[={]/g;
  let match: RegExpExecArray | null;

  while ((match = exportPattern.exec(content)) !== null) {
    const originalName = match[2];
    const pascalName = toPascalCase(originalName);
    if (originalName !== pascalName) {
      typeMap.set(originalName, pascalName);
    }
  }

  // Replace all exported declarations
  for (const [original, pascal] of typeMap.entries()) {
    // Escape special regex characters in original name
    const escapedOriginal = original.replaceAll('$', String.raw`\$`);
    // Replace export declarations
    content = content.replaceAll(
      new RegExp(
        String.raw`export\s+(interface|type)\s+${escapedOriginal}\s*([={])`,
        'g',
      ),
      `export $1 ${pascal} $2`,
    );
  }

  // Replace all references to renamed types
  for (const [original, pascal] of typeMap.entries()) {
    const escapedOriginal = original.replaceAll('$', String.raw`\$`);
    // Replace references like: originalName["something"]
    content = content.replaceAll(
      new RegExp(String.raw`\b${escapedOriginal}\["`, 'g'),
      `${pascal}["`,
    );
    // Replace references like: : originalName[
    content = content.replaceAll(
      new RegExp(String.raw`:\s*${escapedOriginal}\[`, 'g'),
      `: ${pascal}[`,
    );
  }

  // Prepend our custom header
  content = CUSTOM_HEADER + '\n' + content;

  // Write the file back
  writeFileSync(OUTPUT_FILE, content, 'utf8');

  // Run prettier to format the file according to project conventions
  console.info('Running prettier to format the generated file...');
  execSync(`npx prettier --write ${OUTPUT_FILE}`, {
    stdio: 'inherit',
  });

  console.info('✅ Types generated successfully with custom header!');
} catch (error) {
  console.error(
    '❌ Error generating types:',
    error instanceof Error ? error.message : String(error),
  );
  process.exit(1);
}
