#!/bin/sh
# Greenbone Security Assistant
# $Id$
# Description: Utility to generate a pot file from gsa JavaScript i18n
#
# Authors:
#  Björn Ricks <bjoern.ricks@greenbone.net>
#
# Copyright:
#  Copyright (C) 2016 - 2017 Greenbone Networks GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

if [ $# -lt 3 ]; then
  echo "Missing required parameters" > 2;
  exit 1;
fi

SOURCE_BASEDIR=$1
POT_FILE=$2
SOURCE_DIR=$3

mkdir -p `dirname $POT_FILE`

cd "$SOURCE_BASEDIR" || exit 2
SOURCES=`find $SOURCE_DIR -name "*.js" -not -path "*/node_modules/*" -not -path "*/build/*"`

xgettext --from-code=UTF-8 -o "$POT_FILE" -L JavaScript $SOURCES
