name: 'Dependency Review'
on: [pull_request]

# cancel eventually still running jobs for the same branch and workflow
# to save resources.
#
# NOTE:
# This *can* lead to the effect that the first job that fails due to an
# error introduced by a commit is *not* the run for the same commit but a later one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dependency Review'
        uses: greenbone/actions/dependency-review@v3
