name: Remove Pull Request Container Image Builds

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  remove-container-image:
    permissions:
      packages: write
    name: Remove container image
    runs-on: ubuntu-latest
    steps:
      - name: Remove container image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: |
          gh api -X DELETE /orgs/${{ github.repository_owner }}/packages/container/${{ github.repository }}/${{ github.event.pull_request.head.ref }}
