name: SBOM upload
on:
  workflow_dispatch:
  push:
    branches: ["main"]

# cancel eventually still running jobs for the same branch and workflow
# to save resources.
#
# NOTE:
# This *can* lead to the effect that the first job that fails due to an
# error introduced by a commit is *not* the run for the same commit but a later one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  SBOM-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: 'SBOM upload'
        uses: greenbone/actions/sbom-upload@v3
